### ISSUE TITLE
UnhandledPromiseRejectionWarning: MongoParseError: option usecreateindex is not supported

### ISSUE THREAD

**Issue by otaciobarbosa** [otaciobarbosa/mongoose-find-function#1]
$ node index.js 
(node:15696) UnhandledPromiseRejectionWarning: MongoParseError: option usecreateindex is not supported
    at Object.parseOptions (C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongodb\lib\connection_string.js:291:15)
    at new MongoClient (C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongodb\lib\mongo_client.js:62:46)
    at C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongoose\lib\connection.js:779:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongoose\lib\connection.js:776:19)
    at C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongoose\lib\index.js:330:10
    at C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\TI\Desktop\mongoose-find-function\node_modules\mongoose\lib\index.js:1151:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by otaciobarbosa** [comment]
mongoose.connect('mongodb://127.0.0.1:27017/geeksforgeeks', {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true
});

Removido: useCreateIndex: true,

mongoose.connect('mongodb://127.0.0.1:27017/geeksforgeeks', {
    useNewUrlParser: true,
    useUnifiedTopology: true
});
